retail:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/manager
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/retail
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: ts4PkutEaAyM8NP1HN9Z5W1V4MNAShnq
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt