spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: postgres
    password: catalogue
  #с какими схемами будет работать flywaydb
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL8Dialect
server:
  port: 8081