spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: postgres
    password: pass
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
    user:
      name: catalogue_service_user
      password: '{noop}pass'
      roles:
        - SERVICE
server:
  port: 8081
logging:
  level:
    sql: info